modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/PanSzelescik/moreplates/issues"
displayURL="https://minecraft.curseforge.com/projects/moreplates"
logoFile="logo.png"
authors="PanSzelescik"
[[mods]]
modId="moreplates"
version="${file.jarVersion}"
displayName="More Plates"
updateJSONURL="https://raw.githubusercontent.com/PanSzelescik/moreplates/master/update.json"
description='''
This mod adds some Gears, Plates and Rods
'''
[[dependencies.moreplates]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moreplates]]
    modId="morelibs"
    mandatory=true
    versionRange="[1.2.2-alpha2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moreplates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"